config/routes.rb
Rails.application.routes.draw do
  resources :users
# pour la resource slides sur le frontend,
# on autorise que la vue index
# les autres vues ne seront pas utilisées
  resources :slides, only: [:index]

  # on crée un namespace admin pour administrer les slides
  namespace :admin do
    resources :slides

    # On ajoute un root dans le namespace pour que
    # http://localhost:3000/admin
    # charge par défaut
    # http://localhost:3000/admin/sliders
    # l'url dans la barre d'adresse restera
    # http://localhost:3000/admin
    root 'slides#index'
  end

  # On crée là aussi un root pour que
  # http://localhost:3000
  # charge http://localhost:3000/sliders
  # l'url dans la barre d'adresse restera
  # http://localhost:3000/

  root 'slides#index'
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  has_attached_file :picture, styles: { original:"1024x720", medium: "500x500>", thumb: "200x200>" }

  # on s'assure que le fichier envoyé sera de type 'image'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  # On vérifie que le fichier aura l'extension 'png', 'jpg', 'jpeg'
  validates_attachment_file_name :picture, matches: [/png\Z/, /jpe?g\Z/]

  # On vérifie que l'image envoyé ne fasse pas plus d'un 1M
  validates_with AttachmentSizeValidator, attributes: :picture, less_than: 1.megabytes

  # on vérifie que les 4 champs seront bien rempli
  validates :name, :desc, :author, :picture, presence: true
  # on crée 2 scopes pour simplifier la synthaxe du controller
  # on recherche que les publication à 'true'
  scope :publication, -> {
     where(published: true)
   }
  # on cherche les publications dont la date du jour est comprise dans les dates de publication
  scope :min_publication, -> {
     where('DateTime(published_from) <= ? ', DateTime.now )
   }
  scope :max_publication, -> {
     where('DateTime(published_to) >= ?', DateTime.now )
   }
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to admin_slide_path(@slide), notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to admin_slide_path, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :desc, :author, :picture, :published, :published_to, :published_from)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController


  # GET /slides
  # GET /slides.json
  def index


    @slides = Slide.publication.min_publication.max_publication
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :crypted_password, :salt)
    end
end

app/helpers/admin/slides_helper.rb
module Admin::SlidesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/slides/_form.html.erb
<%= form_for [:admin,@slide], html: { multipart: true }  do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :published_from %><br>
    <%= f.date_select :published_from %>
  </div>
  <div class="field">
    <%= f.label :published_to %><br>
    <%= f.date_select :published_to %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/slides/edit.html.erb
<h1>Editing Slide</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_slides_path(@slide) %> |
<%= link_to 'Back', slides_path %>

app/views/admin/slides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Slides</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <td>
        <tr><%= image_tag slide.picture.url(:medium) %></tr>
      </td>
      <tr>
        <td><%= slide.name %></td>
        <td><%= slide.desc.html_safe %></td>
        <td><%= slide.author.html_safe %></td>
        <td><%= link_to 'Show', admin_slide_path(slide) %></td>
        <td><%= link_to 'Edit', edit_admin_slide_path(slide) %></td>
        <td><%= link_to 'Destroy', admin_slide_path(slide), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= slide.published %></td>
        <td><%= slide.published_to %></td>
        <td><%= slide.published_from %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_admin_slide_path %>

app/views/admin/slides/new.html.erb
<h1>New Slide</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_slides_path %>

app/views/admin/slides/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @slide.picture.url(:medium)%>
<p>
  <strong>Name:</strong>
  <%= @slide.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @slide.desc %>
</p>

<p>
  <strong>Author:</strong>
  <%= @slide.author %>
</p>

<%= link_to 'Edit', edit_admin_slide_path(@slide) %> |
<%= link_to 'Back', admin_slide_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomepageWeezart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/slides/index.html.erb
<h1>Listing Slides</h1>


<div class="slides">
  <% @slides.each do |slide| %>
    <div class="slide">
      <p>
        <%= slide.desc %>
      </p>
      <p>
        <%= slide.author %>
      </p>
      <p>
        <%= image_tag slide.picture.url(:original) %>
      </p>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :crypted_password %><br>
    <%= f.text_field :crypted_password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br>
    <%= f.text_field :salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>